### ISSUE TITLE
.net core library to convert 3D step file to gltf file format 

### ISSUE THREAD

**Issue by ashwinianbhore** [xBimTeam/XbimGltf#7] opened 2020-01-30 12:38 UTC
Any Open-source Libraries available to Convert 3D STEP files to glTF file format?

**Comment by CBenghi** [comment] 2020-01-31 11:26
Duplicate of https://github.com/xBimTeam/XbimGltf/issues/8

**Closed by CBenghi** 2020-01-31 11:26 UTC
